stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SCHEDULER_PARAMETERS: "-P CSC371 -W 0:45 -nnodes 1"

.batch-runner:
  tags: [batch]
  rules:
  - if: '$CI_PIPELINE_SOURCE == "web"'

build:batch:
  variables:
  stage: build
  extends: .batch-runner
  before_script:
    - module load autoconf
    - module load automake
    - module load libtool
    - module load python
  script:
    - rm -rf $HOME/software/ci-build
    - ./autogen.sh
    - module load cuda
    - ./configure --with-device=ch4:ucx --with-ucx=embedded --prefix=$HOME/software/ci-build --with-cuda=$CUDAPATH --with-pm=none --with-pmix=$MPI_ROOT --with-hwloc=embedded
    - make -j install
    - $HOME/software/ci-build/bin/mpicc -o $HOME/software/ci-build/bin/cpi examples/cpi.c
    - cd $HOME
    - echo $LD_LIBRARY_PATH
    - ls $CUDAPATH
    - export LD_LIBRARY_PATH=$CUDAPATH/lib64:$MPI_ROOT/lib:$LD_LIBRARY_PATH
    - ldd software/ci-build/bin/cpi
    - jsrun -n 2 -r 2 -a 1 -g 1 --smpiargs="-disable_gpu_hooks" $HOME/software/ci-build/bin/cpi
