# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true
- script: |
    export MPICH_DEPS_PREFIX=$HOME/autotools
    export PATH=$MPICH_DEPS_PREFIX/bin:$PATH
    ./maint/bootstrap.sh
    ./autogen.sh
  displayName: 'autogen'
- script: |
    ./configure
  displayName: 'configure'
- script: |
    make -j
  displayName: 'make'
