name: MPICH Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, macos-latest]

    steps:
    - name: install Linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install gfortran
    - name: install macOS dependencies
      if: runner.os == 'macOS'
      run: brew install autoconf automake libtool gcc
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --prefix=$PWD/i
    - name: make
      run: make -j 2
    - name: make install
      run: make install
    - name: cpi
      run: i/bin/mpiexec -n 2 ./examples/cpi
